--SQL Advance Case Study


--Q1--BEGIN --> List all the states in which we have customers who have bought cellphones 

from 2005 till today.
SELECT [State] 
FROM FACT_TRANSACTIONS T1
INNER JOIN DIM_LOCATION T2 ON T1.IDLOCATION= T2.IDLOCATION
INNER JOIN DIM_MODEL T3 ON T1.IDMODEL= T3.IDMODEL
WHERE Date BETWEEN '01-01-2005' AND GETDATE() 
GROUP BY STATE




--Q1--END

--Q2--BEGIN -->  What state in the US is buying the most 'Samsung' cell phones?
	
SELECT TOP 1 
STATE FROM DIM_LOCATION
INNER JOIN FACT_TRANSACTIONS ON DIM_LOCATION.IDLOCATION=FACT_TRANSACTIONS.IDLOCATION
INNER JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDMODEL = DIM_MODEL.IDMODEL
INNER JOIN DIM_MANUFACTURER ON DIM_MANUFACTURER.IDMANUFACTURER= DIM_MODEL.IDMANUFACTURER
WHERE MANUFACTURER_NAME = 'Samsung'
GROUP BY STATE
ORDER BY SUM(QUANTITY) DESC


--Q2--END

--Q3--BEGIN -->  Show the number of transactions for each model per zip code per state. 
	

SELECT MODEL_NAME, ZIPCODE, STATE, COUNT(IDCUSTOMER) AS NO_OF_TRANSACTIONS FROM DIM_LOCATION
INNER JOIN FACT_TRANSACTIONS ON DIM_LOCATION.IDLOCATION=FACT_TRANSACTIONS.IDLOCATION
INNER JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDMODEL = DIM_MODEL.IDMODEL
GROUP BY MODEL_NAME, ZIPCODE, STATE


--Q3--END

--Q4--BEGIN --> Show the cheapest cellphone (Output should contain the price also)

SELECT TOP 1
MODEL_NAME,UNIT_PRICE FROM DIM_MODEL
ORDER BY IDMODEL


--Q4--END

--Q5--BEGIN -->  Find out the average price for each model in the top5 manufacturers in terms of sales quantity and order by average price.

SELECT MODEL_NAME, AVG(UNIT_PRICE) AS AVG_PRICE FROM DIM_MODEL
INNER JOIN DIM_MANUFACTURER ON DIM_MANUFACTURER.IDMANUFACTURER = DIM_MODEL.IDMANUFACTURER
WHERE MANUFACTURER_NAME IN 
(
SELECT TOP 5 MANUFACTURER_NAME FROM FACT_TRANSACTIONS 
INNER JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDMODEL = DIM_MODEL.IDMODEL
INNER JOIN DIM_MANUFACTURER ON DIM_MANUFACTURER.IDMANUFACTURER = DIM_MODEL.IDMANUFACTURER
GROUP BY MANUFACTURER_NAME
ORDER BY SUM(QUANTITY)
)
GROUP BY MODEL_NAME
ORDER BY AVG(UNIT_PRICE) DESC



--Q5--END

--Q6--BEGIN --> List the names of the customers and the average amount spent in 2009, where the average is higher than 500

SELECT CUSTOMER_NAME, AVG(TOTALPRICE) AVG_SPENT
FROM DIM_CUSTOMER
INNER JOIN FACT_TRANSACTIONS ON DIM_CUSTOMER.IDCUSTOMER = FACT_TRANSACTIONS.IDCUSTOMER
WHERE YEAR(Date) = 2009 
GROUP BY CUSTOMER_NAME
HAVING AVG(TOTALPRICE)>500



--Q6--END
	
--Q7--BEGIN  --> . List if there is any model that was in the top 5 in terms of quantity, simultaneously in 2008, 2009 and 2010 



SELECT * 
FROM (
SELECT TOP 5 MODEL_NAME FROM FACT_TRANSACTIONS AS T3
INNER JOIN DIM_MODEL T2 ON T2.IDModel = T3.IDMODEL
INNER JOIN DIM_MANUFACTURER T1 ON T1.IDManufacturer = T2.IDManufacturer
WHERE YEAR (DATE) = 2008
GROUP BY  T3.IDModel, Model_Name
ORDER BY SUM(Quantity) DESC

INTERSECT

SELECT TOP 5 MODEL_NAME FROM FACT_TRANSACTIONS AS T3
INNER JOIN DIM_MODEL T2 ON T2.IDModel = T3.IDMODEL
INNER JOIN DIM_MANUFACTURER T1 ON T1.IDManufacturer = T2.IDManufacturer
WHERE YEAR (DATE) = 2009
GROUP BY  T3.IDModel, Model_Name
ORDER BY SUM(Quantity) DESC

INTERSECT

SELECT TOP 5 MODEL_NAME FROM FACT_TRANSACTIONS AS T3
INNER JOIN DIM_MODEL T2 ON T2.IDModel = T3.IDMODEL
INNER JOIN DIM_MANUFACTURER T1 ON T1.IDManufacturer = T2.IDManufacturer
WHERE YEAR (DATE) = 2010
GROUP BY  T3.IDModel, Model_Name
ORDER BY SUM(Quantity) DESC) AS Y





--Q7--END

--Q8--BEGIN --> Show the manufacturer with the 2nd top sales in the year of 2009 and the manufacturer with the 2nd top sales in the year of 2010



WITH RANK1 AS
              (
			    SELECT MANUFACTURER_NAME, YEAR(DATE) AS YEAR ,
				DENSE_RANK() OVER (PARTITION BY YEAR (DATE) ORDER BY SUM (TOTALPRICE) DESC) AS RANK
				FROM FACT_TRANSACTIONS AS X 
				INNER JOIN DIM_MODEL AS Y
				ON X.IDModel = Y.IDModel
				INNER JOIN DIM_MANUFACTURER AS Z
				ON Z.IDManufacturer = Y.IDManufacturer
				GROUP BY Manufacturer_Name, YEAR(DATE)
				)
				SELECT YEAR , MANUFACTURER_NAME
				FROM RANK1
				WHERE YEAR IN ('2009','2010') AND RANK = '2'




--Q8--END
--Q9--BEGIN --> Show the manufacturers that sold cellphones in 2010 but did not in 2009.
	
SELECT MANUFACTURER_NAME FROM DIM_MANUFACTURER T1
INNER JOIN DIM_MODEL T2 ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS T3 ON T2.IDMODEL= T3.IDMODEL
WHERE YEAR(Date) = 2010 
EXCEPT 
SELECT MANUFACTURER_NAME FROM DIM_MANUFACTURER T1
INNER JOIN DIM_MODEL T2 ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS T3 ON T2.IDMODEL= T3.IDMODEL
WHERE YEAR(Date) = 2009


--Q9--END

--Q10--BEGIN --> Find top 100 customers and their average spend, average quantity by each year. Also find the percentage of change in their spend.

WITH TOP10 
AS(
SELECT * 
FROM(
SELECT YEAR(DATE) AS YEARS, IDCUSTOMER, AVG(TOTALPRICE) AS AVG_SPEND, AVG(QUANTITY) AS AVG_QTY,
DENSE_RANK() OVER (PARTITION BY YEAR(DATE) ORDER BY AVG(TOTALPRICE)DESC) AS RANKS
FROM FACT_TRANSACTIONS
GROUP BY IDCUSTOMER, YEAR(DATE)
) AS X
WHERE RANKS<=10),

SPEND_YEAR_WISE AS (

           SELECT IDCUSTOMER,YEARS, AVG_SPEND, AVG_QTY,
		   LAG(AVG_SPEND,1) OVER (PARTITION BY IDCUSTOMER ORDER BY IDCUSTOMER,YEARS) AS PREV_SPEND FROM TOP10),

		   PRECENT_CHANGE AS (SELECT *, (AVG_SPEND - PREV_SPEND)/PREV_SPEND * 100 AS [YOY %CHANGE]
		                     FROM SPEND_YEAR_WISE)

		SELECT IDCUSTOMER ,YEARS AVG_QTY, AVG_SPEND, [YOY %CHANGE]
		FROM PRECENT_CHANGE


	

--Q10--END
	
